---

- name: Create ecs predictor service
  ecs_service:
    state: present
    name: "{{predictor_service_name}}"
    cluster: "{{cluster_name}}"
    task_definition: "{{predictor_task_name}}:{{taskdef.taskdefinition.revision}}"
    desired_count: "{{desired_count}}"
    region: eu-central-1
    launch_type: FARGATE
    network_configuration:
      subnets:
      security_groups:
      assign_public_ip: yes
    deployment_configuration:
      minimum_healthy_percent: 50
      maximum_percent: 200

- name: Create ecs processor service
  ecs_service:
    state: present
    name: "{{processor_service_name}}"
    cluster: "{{cluster_name}}"
    task_definition: "{{processor_task_name}}:{{processordef.taskdefinition.revision}}"
    desired_count: "{{desired_count}}"
    region: eu-central-1
    launch_type: FARGATE
    network_configuration:
      subnets:
      security_groups:
      assign_public_ip: yes
    deployment_configuration:
      minimum_healthy_percent: 50
      maximum_percent: 200